export const CompIndustry=[
    {
        id:1,
        name:"Navbar",
        link:"nav",
    },
    // {
    //     id:2,
    //     name:"Alerts",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/alert_HZATk5sLb.svg',
    //     link:"alert",
    // },
    // {
    //     id:3,
    //     name:"Address",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/address_5zSNjfeul.svg',
    //     link:"address",
    // },
    // {
    //     id:4,
    //     name:"Admin",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/admin_0_Wz46sdLm.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"#",
    // },
    // {
    //     id:5,
    //     name:"Blog",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/content_Uf5dIyJKT5.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"blog",
    // },
    // {
    //     id:6,
    //     name:"Buttons",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/button_YOKytipH2.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"button",
    // },
    // {
    //     id:7,
    //     name:"Breadcrumbs",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/breadcrumb_EbEbafdbb.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"#",
    // },
    // {
    //     id:8,
    //     name:"Banners",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/banner_qFWhrninx.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"#",
    // },
    // {
    //     id:8,
    //     name:"Call to Action",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/calltoaction_51Ndsn2YW.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"/ctacomp",
    // },
    // {
    //     id:8,
    //     name:"Content",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/blog_LmKIu_a5V.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"#",
    // },
    // {
    //     id:8,
    //     name:"Contact",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/contact_n8VSUzNXy.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"contact",
    // },
    // {
    //     id:8,
    //     name:"Carousel",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/carousel_FX96tQ2q4.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"#",
    // },
    // {
    //     id:8,
    //     name:"Feature",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/featues_C30H8Ge1X.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"/features",
    // },
    // {
    //     id:8,
    //     name:"FAQ",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/faq_MYk1pBSbH.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"faqcomp",
    // },
    // {
    //     id:8,
    //     name:"Forms",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/landing.09fa1de1_s9s7n7yph.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"#",
    // },
    // {
    //     id:8,
    //     name:"Footers",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/breadcrumb_EbEbafdbb.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"footers",
    // },
    // {
    //     id:8,
    //     name:"Navbar",
    //     image:"https://ik.imagekit.io/vpa3fwqdnd/Components/landing.09fa1de1_OtMQk3TRg.svg",
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"#",
    // },
    // {
    //     id:8,
    //     name:"Gallery",
    //     image:"https://ik.imagekit.io/vpa3fwqdnd/Components/landing.09fa1de1_XQPuMCCgk.svg",
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"#",
    // },
    // {
    //     id:8,
    //     name:"Hero",
    //     image:"https://ik.imagekit.io/vpa3fwqdnd/Components/landing.09fa1de1_OtMQk3TRg.svg",
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"hero",
    // },
    // {
    //     id:8,
    //     name:"Pricing",
    //     image:"https://ik.imagekit.io/vpa3fwqdnd/Components/landing.09fa1de1_ER9PdQ_z2.svg",
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"#",
    // },
    // {
    //     id:8,
    //     name:"Pagination",
    //     image:'https://ik.imagekit.io/vpa3fwqdnd/Components/contact_n8VSUzNXy.svg',
    //     about:"All Components are customizable. Customize According to your Design.",
    //     link:"#",
    // },
]